---
directed: false
graph: {}
nodes:
- type: router
  id: router2
  def_list: no
  def_conn: no
  router:
    - mode: interior
      allowUnsettledMulticast: yes
  listener:
    - host: 1.1.1.1
      port: 666
      sslprofile: Test
      role: normal
  connector:
    - host: router2
      port: 111
    - host: router1
      port: 555
  linkRoute:
    - prefix: anycast
      connection: router3
      dir: in
    - prefix: anycast
      connection: router3
      dir: out
  sslProfile:
    - name: Test
      ciphers: AES-256
      password: pass
- type: router
  id: router1
  mode: inter-router
  group: group2
- type: broker
  id: broker2
- type: broker
  id: broker3
- type: broker
  id: broker1
links:
- source: router2
  target: router1
  value: 10
- source: router2
  target: broker2
  value: 5
- source: router2
  target: broker3
  value: 6
- source: router1
  target: broker1
  value: 7
multigraph: false
